/*$(document).ready(function(){
  $(".introduction-img-list img").click(function(){
    $(".selected-img img").attr("src",$(this).attr("src").replace("_eye",""));
    $(".introduction-img-list img").css("opacity", "0.5");
    $(this).css("opacity", "1");

  });


});*/

var detail = {
	'character': {
		 'aragorn' : "In The Fellowship of the Ring, Aragorn joined Frodo Baggins, Bilbo's adopted heir, and three of Frodo's friends at the Inn of the Prancing Pony in Bree; a letter from Gandalf convinced Frodo to trust Aragorn. The four hobbits had set out from the Shire to bring the One Ring to Rivendell.With Aragorn's help the Hobbits escaped the pursuing Nazgul and reached Rivendell. There Frodo volunteered to destroy the Ring in the fires of Mount Doom, and Aragorn was chosen as a member of the Fellowship of the Ring to accompany him.",
		 'frodo' : "The Fellowship of the Ring opens as Frodo came of age (at 33 years old) and Bilbo left the Shire for good on his one hundred and eleventh birthday. Frodo inherited Bag End and Bilbo's ring, which were both introduced in The Hobbit. Frodo kept the Ring hidden for 17 years, resulting in it giving him the same longevity of Bilbo, until Gandalf returned to tell him that it was the One Ring of the Dark Lord Sauron, who desired to use it to conquer Middle-earth.	Realizing that he was a danger to the Shire as long as he remained there with the Ring, Frodo decided to leave home and take the Ring to Rivendell, home of Elrond, a mighty Elf lord...",
		 'gandalf' : "Returning to the Shire, in T.A. 3018, Gandalf confirmed his suspicions by throwing the Ring into Frodo's hearth-fire and reading the writing that appeared on the Ring's surface. He told Frodo the full history of the Ring, and urged him to take the Ring to Rivendell; for he would be in grave danger if he stayed in the Shire. Gandalf said he would attempt to return for Frodo's 50th birthday party, in order to accompany him on the road thereafter; and that meanwhile Frodo should arrange to leave quietly, as the servants of Sauron would be searching for him. Outside the Shire, Gandalf encountered Radagast the Brown, another of the Istari, who brought the news that the Nazgul had ridden forth and crossed the River Anduin—and a request from Saruman that Gandalf come to Isengard. Gandalf left a letter to Frodo at the inn in Bree, and headed towards Isengard. There Saruman revealed his true colours, urging Gandalf to help him obtain the Ring for his own use. Gandalf refused, and Saruman imprisoned him at the top of the tower of Orthanc...",
		 'gimli': "Gimli was a remote descendant of Durin the Deathless, chief of the Seven Fathers of the Dwarves and ancestor to the Dwarven people to which Gimli belonged, the Longbeards. Gimli was introduced at the Council of Elrond Half-elven. Gimli and his father were attending the Council to bring news of their home, Erebor, and to warn that the Dark Lord Sauron was searching for the One Ring.  Frodo volunteered for the task, and Elrond chose eight people of varying races to aid him in his task — including Gimli. Within the Fellowship there was initially friction between Gimli and the elf Legolas, for various reasons: more recently Thranduil, Legolas' father, once imprisoned Gimli's father Gloin.",
		 'gollum': "The Ring, which Gollum referred to as 'my precious' or 'precious', extended his life far beyond natural limits. Centuries of the Ring's influence twisted Gollum's body and mind, and, by the time of the novels, he had 'come to love and hate the Ring, just as he loved and hated himself.'' Throughout the story, Gollum was torn between his lust for the Ring and his desire to be free of it. Bilbo Baggins found the Ring and took it for his own, and Gollum afterwards pursued it for the rest of his life. Gollum finally seized the Ring from Frodo Baggins at the Cracks of Doom in Orodruin in Mordor; but he fell into the fires of the volcano, where both he and the Ring were destroyed.",
		 'legolas': "Legolas was the son of Thranduil, King of the Woodland Realm of Northern Mirkwood,who appears as 'the Elvenking' in The Hobbit. Thranduil ruled over the Silvan Elves or 'Wood-elves' of Mirkwood. Legolas was introduced in The Fellowship of the Ring, at the Council of Elrond in Rivendell, where he came as a messenger from his father to discuss Gollum's escape from their guard.Legolas was chosen to be a member of the Fellowship of the Ring, charged with destroying the One Ring. He accompanied the other members in their travels from Rivendell to Amon Hen, serving as the group's archer.",
		 'ring-ghost': "The Nazgul wore their rings long enough that their physical forms faded away until they had become entirely invisible to mortal eyes. Their black robes gave them visible form. During the assault on Minas Tirith, the leader of the Nine, the Witch-king of Angmar, cast back his hood to reveal a crown, but the head that wore it was invisible. While wearing the One Ring, Frodo perceived them as pale figures robed in white, with 'haggard hands' and wearing crowns. In The Fellowship of the Ring they were armed with steel swords, while the Witch-king wielded a Morgul blade that could turn its victim into a wraith. During the Battle of the Pelennor Fields, the Witch-king bore a 'long pale sword', and later used a mace against Eowyn.",
		 'samwise-gamgee': "Samwise Gamgee is first introduced in The Fellowship of the Ring. Sam is Frodo Baggins' gardener, having inherited the position as Baggins' gardener from his father, Hamfast 'Gaffer' Gamgee. As 'punishment' for eavesdropping on Gandalf's conversation with Frodo regarding the One Ring, Sam was made Frodo's first companion on his journey to Rivendell. They were joined by Meriadoc Brandybuck and Peregrin Took, Frodo's cousins, and journeyed together to Rivendell, where the Council of Elrond took place and Sam joined the Fellowship of the Ring.",
		 'sauron': "the reorganizing and rehabilitation of Middle-earth, 'neglected by the gods,' Sauron  becomes a reincarnation of Evil, and a thing lusting for Complete Power', eventually rising to become 'master and god of Men'. Gandalf deduced that the ring that Bilbo had found in Gollum's cave was indeed Sauron's lost Master-ring. He informed Frodo about the true nature of the heirloom Bilbo had left for him, and its terrible potential if Sauron should ever regain it: 'The Enemy still lacks one thing to give him strength and knowledge to beat down all resistance, break the last defences, and cover all the lands in a second darkness. He lacks the One Ring... So he is seeking it, seeking it, and all his thought is bent on it.' Gandalf went for advice to Saruman, but discovered that he had been corrupted by his long studies of Sauron. Using the palantir in the tower of Orthanc, Saruman was now in communication with the Dark Lord and acted as his ally, though he also secretly hoped to take the Ring for himself and use its power to supplant Sauron."
	},
	'race' : {
		'dwarves' : "The Dwarves are a race inhabiting Middle-earth. They are based on the dwarfs of Germanic myths: small humanoids that dwell in mountains, and are associated with mining, metal-craft and jewelry. the Dwarves are described as shorter and stockier than Elves and Men, able to withstand both heat and cold. Though they are mortal, Dwarves have an average lifespan of 250 years.They breed slowly, for no more than a third of them are female, and not all marry; also, female Dwarves look and sound (and dress, if journeying—which is rare) so alike to Dwarf-males that other folk cannot distinguish them, and thus others wrongly believe Dwarves grow out of stone.",
		'elves' : "Elves are naturally immortal, and remain unwearied with age. In addition to their immortality, Elves can recover from wounds which would normally kill a mortal Man. However, Elves can be slain, or die of grief and weariness. Elves marry freely and for love early in life. Monogamy is practiced and adultery is unthinkable; they marry only once .If they do not die in battle or from some other cause, the Elves of Middle-earth grow weary of it and desire to go to Valinor, where the Valar originally sheltered their kind.",
		'ents' : "The Ents appear as ancient shepherds of the forest and allies of the free peoples of Middle-earth. large Man-like, almost Troll-like, figure, at least fourteen foot high, very sturdy, with a tall head, and hardly any neck. Whether it was clad in stuff like green and grey bark, or whether that was its hide, was difficult to say. At any rate the arms, at a short distance from the trunk, were not wrinkled, but covered with a brown smooth skin. The large feet had seven toes each. The lower part of the long face was covered with a sweeping grey beard, bushy, almost twiggy at the roots, thin and mossy at the ends.",
		'hobbits' : "Hobbits are a diminutive, humanoid race who inhabit the lands of Middle-earth. They are also referred to as Halflings. Hobbits are not quite as stocky as the similarly-sized dwarves, but still tend to be stout, with slightly pointed ears. Hobbits are between two and four feet tall, the average height being three feet six inches. They dress in bright colours, favouring yellow and green. Nowadays, they are usually shy, but are nevertheless capable of great courage and amazing feats under the proper circumstances. They are adept with slings and throwing stones. For the most part, they cannot grow beards, but a few of the race of Stoor can. Their feet are covered with curly hair with leathery soles, so most hobbits hardly ever wear shoes. The race's average life expectancy is 100 years.",
		'maiar' : "The Maiar (singular: Maia)  are lesser Ainur who entered Ea in the beginning of time. The name Maiar is in the Quenya tongue and comes from the Elvish root maya- 'excellent, admirable'. Being of divine origin and possessing great power, the Maiar can wander the world unseen or shape themselves in fashion of Elves or other creatures; these 'veils', called fanar in Quenya, could be destroyed, but their true-being could not. Rarely did the Maiar adopt their visible forms to elves and man, and for that reason, very few of the Maiar have names in their tongues, and the elves do not know how many of the Maiar exist. Melkor (known in Sindarin as Morgoth), the evil Vala, corrupted many Maiar into his service. These included Sauron and the Balrogs, his demons of flame and shadow.These are called in Quenya Umaiar.",
		'man' : "The terms Man and Men refer to humankind – in contrast to Elves, Dwarves, Orcs, and other humanoid races – and does not denote gender. Men bear the Gift of Men, mortality. Elves are immortal, in the sense that they do not perceivably age, and even if their bodies are slain, their spirits remain bound to the world, going to the Halls of Mandos, where they are later re-embodied; a cycle that will perpetuate for them until the world ends. Although all Men are related to one another, there are many different groups with different cultures."
	},
	'series' : {
		'The Fellowship Of The Ring' : "In the Second Age of Middle-earth, the Dark Lord Sauron forges the One Ring in Mount Doom to conquer all, abandoning a great part of his power to it in order to dominate, through it, at a distance, the other Rings of Power, which had been granted to lords of Elves, Dwarves and Men. An army of men and elves battle Sauron’s forces in Mordor, where Prince Isildur of Gondor cuts the One Ring off of Sauron's finger, thereby temporarily destroying his physical shape, and decides to take care of the Ring himself, but the evil influence of the Ring corrupts Isildur, preventing him from destroying it in Mount Doom. Isildur is later killed by Orcs, and the Ring is lost for 2,500 years, found and owned by Gollum for five centuries. The Ring is then found by a Hobbit named Bilbo Baggins.",
		'The Two Tower' : "Frodo Baggins and Samwise Gamgee continue their journey to Mordor to destroy the One Ring by throwing it into Mount Doom. They are attacked in the night by Gollum, former owner of the Ring, but they capture him. Sympathising with Gollum for what he perceives as their shared burden, Frodo asks Gollum to lead them safely to Mordor, despite Sam’s objections. Meanwhile, Aragorn, Legolas, and Gimli pursue the Uruk-hai who kidnapped their friends Merry and Pippin. The Uruk-hai are slaughtered by the Rohirrim, army of Rohan, but the two Hobbits escape into Fangorn Forest where they meet the Ent Treebeard. Aragorn’s group later meet the Rohirrim who have been banished by their king Theoden, who is being manipulated by Saruman’s servant Grima Wormtongue. Tracking the Hobbits in Fangorn, Aragorn’s group encounter a resurrected Gandalf who perished in Moria, but was revived to help save Middle-earth.",
		'The Return Of The King' : "Gandalf leads Aragorn, Legolas, Gimli, and King Theoden to Isengard where they reunite with Merry and Pippin. With Saruman defeated, Gandalf retrieves Saruman's palantir. Pippin later steals a glance into the seeing-stone, and suffers a mental attack from Sauron himself. Gandalf deduces that Sauron will attack Gondor's capital Minas Tirith. He rides there to warn them, taking Pippin with him because Sauron believes Pippin is the ring bearer.",
		'The Hobbit': "Bilbo and the Dwarves watch from the Lonely Mountain as the dragon Smaug sets Laketown ablaze. Bard the Bowman breaks out of prison, and eventually kills Smaug with the black arrow brought to him by his son Bain. Smaug's falling body crushes the fleeing Master of Laketown, who was escaping Laketown on a boat laden with the town's gold. Bard reluctantly becomes the new leader of the people of Laketown, as they seek refuge in the ruins of Dale, while Legolas travels to investigate Mount Gundabad with Tauriel. Thorin, now struck with 'dragon sickness' over the vast treasure in the mountain, searches obsessively for the Arkenstone, which Bilbo had previously found but kept hidden. Thorin, hearing that Laketown survivors have fled to Dale, orders the entrance of the Lonely Mountain sealed off."
	}

};

$(document).ready(function() {
	$(function(){
		$(".introduction-img-list li").first().find("img").css("opacity", 1);
		var title = $('title').text().toLowerCase();
		if(title == 'character')
			Update(title, 'aragorn');	
		else if(title == 'race')
			Update(title, 'dwarves');
		else
			Update(title,'The Fellowship Of The Ring');
	});

	$(".introduction-img-list img").click(function() { 
		var title = $('title').text().toLowerCase();
		var name = $(this).attr("name");
		$(".introduction-img-list img").removeAttr("style");
		$(this).css("opacity", 1);
		Update(title, name);

		console.log(title);
		console.log(name);
		console.log(detail[title][name]);
	});
});

function Update(title, name) {
	$(".selected-img img").attr("src", "image/"+title+"/"+name+".jpg");
	$(".introduction-content > h3").text(name);
	$(".introduction-content > p").text(detail[title][name]);
}
